In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
dataset = pd.read_csv('Telco-Customer-Churn.csv')


In [ ]:
print(dataset.isnull().sum())
print(dataset.describe())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64
       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000


In [ ]:
dataset['TotalCharges'] = pd.to_numeric(dataset['TotalCharges'],errors='coerce')
dataset['TotalCharges'].fillna(dataset['TotalCharges'].median(),inplace=True)

/tmp/ipykernel_2259/3887026666.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset['TotalCharges'].fillna(dataset['TotalCharges'].median(),inplace=True)


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
categorical_cols = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService',
                    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
                    'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'Churn']
for col in categorical_cols:
  dataset[col] = encoder.fit_transform(dataset[col])

In [ ]:
dataset['Contract'].unique()

array([0, 1, 2])

In [ ]:
import math
dataset['tenureContract'] = dataset['tenure']*dataset['Contract']
dataset['ChargeRatio'] = (dataset['MonthlyCharges']/dataset['TotalCharges'])

In [ ]:
X = dataset.drop(columns=['customerID','Churn'])
y = dataset['Churn']

In [ ]:
print(X)

      gender  SeniorCitizen  Partner  ...  TotalCharges  tenureContract  ChargeRatio
0          0              0        1  ...         29.85               0     1.000000
1          1              0        0  ...       1889.50              34     0.030140
2          1              0        0  ...        108.15               0     0.497920
3          1              0        0  ...       1840.75              45     0.022980
4          0              0        0  ...        151.65               0     0.466205
...      ...            ...      ...  ...           ...             ...          ...
7038       1              0        1  ...       1990.50              24     0.042602
7039       0              0        1  ...       7362.90              72     0.014016
7040       0              0        1  ...        346.45               0     0.085438
7041       1              1        1  ...        306.60               0     0.242661
7042       1              0        0  ...       6844.50          

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [ ]:
print(X_train)

      gender  SeniorCitizen  Partner  ...  TotalCharges  tenureContract  ChargeRatio
2920       0              0        1  ...       6155.40             144     0.013825
2966       0              1        0  ...        672.70               0     0.068901
6099       0              0        1  ...       1810.55             142     0.013642
5482       1              0        1  ...       2405.05              33     0.030727
2012       0              0        1  ...       4533.70               0     0.021781
...      ...            ...      ...  ...           ...             ...          ...
4931       1              0        1  ...       1539.80               0     0.067184
3264       0              0        0  ...        964.35               0     0.094468
1653       1              0        1  ...       1185.95             116     0.017497
2607       1              1        0  ...         69.75               0     1.000000
2732       0              0        0  ...         94.50          

In [ ]:
print(y)

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64


In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit_transform(X_train)
scaler.transform(X_test)

array([[-1.        , -0.4397627 , -0.96854556, ..., -0.54691104,
        -0.33434349, -0.36243702],
       [ 1.        , -0.4397627 , -0.96854556, ...,  2.09892224,
         0.47765214, -0.50134188],
       [-1.        , -0.4397627 , -0.96854556, ..., -0.60040717,
        -0.71063415, -0.28365096],
       ...,
       [-1.        ,  2.27395367, -0.96854556, ...,  1.82104199,
         0.39843306, -0.49814609],
       [ 1.        , -0.4397627 , -0.96854556, ..., -0.58013681,
        -0.71063415, -0.35420997],
       [ 1.        , -0.4397627 , -0.96854556, ..., -0.98732875,
        -0.71063415,  2.98885671]])

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 500,criterion='gini',max_depth=50,min_samples_split=4,max_features='sqrt')
classifier.fit(X_train,y_train)


RandomForestClassifier(max_depth=50, min_samples_split=4, n_estimators=500)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[923 118]
 [185 183]]


0.7849538679914834

In [ ]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
print("Accuracy: {:.2f} %".format(accuracies.mean()*100))
print("Standard Deviation: {:.2f} %".format(accuracies.std()*100))

Accuracy: 79.89 %
Standard Deviation: 1.34 %


In [ ]:
from sklearn.model_selection import GridSearchCV
parameters_rf = [{'n_estimators':[100,200,300,400],'criterion':['gini','entropy'],'max_depth': [None, 5, 10, 30, 50],'min_samples_split': [2, 5, 10],
                  'min_samples_leaf':[1, 2, 4],'max_features': ['sqrt', 'log2', None],'bootstrap': [True, False]}]
grid_search_rf = GridSearchCV(estimator=classifier,
                           param_grid=parameters_rf,
                           scoring='accuracy',
                           cv=5,
                           n_jobs=-1)
grid_search_rf.fit(X_train, y_train)
best_accuracy_rf = grid_search_rf.best_score_
best_parameters_rf = grid_search_rf.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy_rf*100))
print("Best Parameters:", best_parameters_rf)

KeyboardInterrupt: 